services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: orders_api
      POSTGRES_DB: orders
      SCHEMA: orders
    volumes:
      - .docker/postgres:/data/postgres
    ports:
      - "5432:5432"
  goapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app